return [[
<!doctype html>
<html lang="en">
<head>
    <title>Code coverage report for {{filename}}</title>
    <meta charset="utf-8" />
    <style>{{{css}}}</style>
</head>
<body>
    <div class='wrapper'>
        <div>
            <h1>
                <a href="{{{link.root}}}">All files</a> /
                <a href="{{{link.package}}}">{{path}}</a> {{basename}}
            </h1>
            <div>
                <div class="stats">
                    <span class="strong">{{{package.rate}}}%</span>
                    <span class="quiet">Rate</span>
                </div>
                <div class="stats">
                    <span class="strong">{{{package.hits}}}</span>
                    <span class="quiet">Hits</span>
                </div>
                <div class="stats">
                    <span class="strong">{{{package.miss}}}</span>
                    <span class="quiet">Missed</span>
                </div>
            </div>
            <div class='status' data-status="{{status}}"></div>
        </div>
        <div class="package">
            <table>
                <thead>
                    <tr>
                        <th>File</th>
                        <th></th>
                        <th>Rate</th>
                        <th>Hits</th>
                        <th>Missed</th>
                    </tr>
                </thead>
                {{#classes}}
                <tr data-status="{{status}}">
                    <td><a href="{{{report}}}.html">{{name}}</a></td>
                    <td><div class="chart" data-status="{{status}}"><div class="chartfill" style="width:{{{rateTo100Formatted}}}%;"></div></div></td>
                    <td class="num">{{rateFormatted}}%</td>
                    <td class="num">{{hits}}</td>
                    <td class="num">{{miss}}</td>
                </tr>
                {{/classes}}
            </table>
        </div>
        <div class="footer quiet">Code coverage generated by <a href="https://keplerproject.github.io/luacov/" target="_blank">LuaCov</a> at {{datetime}}</div>        
    </div>
</body>
</html>
]]